# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  newsbuswatcherservice:
    image: newsbuswatcherservice
    build:
      context: .
      dockerfile: NewsBus.WatcherService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "NewsBusCosmosDbConnectionString=${NewsBusCosmosDbConnectionString}"
      - "NewsBusQueueConnectionString=${NewsBusQueueConnectionString}"
      - "NewsBusStorageConnetionString=${NewsBusStorageConnetionString}"
    ports:
      - 5002:5000
      - 5003:5001
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  newsbusdownloaderservice:
    image: newsbusdownloaderservice
    build:
      context: .
      dockerfile: NewsBus.DownloaderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "NewsBusCosmosDbConnectionString=${NewsBusCosmosDbConnectionString}"
      - "NewsBusQueueConnectionString=${NewsBusQueueConnectionString}"
      - "NewsBusStorageConnetionString=${NewsBusStorageConnetionString}"
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
