# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  newsbuswatcherservice:
    image: newsbuswatcherservice
    build:
      context: .
      dockerfile: NewsBus.WatcherService/Dockerfile
    environment:
      - "NewsBusCosmosDbConnectionString=${NewsBusCosmosDbConnectionString}"
      - "NewsBusQueueConnectionString=${NewsBusQueueConnectionString}"
      - "NewsBusStorageConnetionString=${NewsBusStorageConnetionString}"
    ports:
      - 8001:80

  newsbusdownloaderservice:
    image: newsbusdownloaderservice
    build:
      context: .
      dockerfile: NewsBus.DownloaderService/Dockerfile
    environment:
      - "NewsBusCosmosDbConnectionString=${NewsBusCosmosDbConnectionString}"
      - "NewsBusQueueConnectionString=${NewsBusQueueConnectionString}"
      - "NewsBusStorageConnetionString=${NewsBusStorageConnetionString}"
    ports:
      - 8000:80
