# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  newsbus.watcherservice:
    image: mental001/newsbuswatcherservice
    build:
      context: ../../
      dockerfile: src/NewsBus.WatcherService/Dockerfile
    environment:
      - "NewsBusCosmosDbConnectionString=${NewsBusCosmosDbConnectionString}"
      - "NewsBusQueueConnectionString=${NewsBusQueueConnectionString}"
      - "NewsBusStorageConnetionString=${NewsBusStorageConnetionString}"
    ports:
      - 8001:80

  newsbus.downloaderservice:
    image: mental001/newsbusdownloaderservice
    build:
      context: ../../
      dockerfile: src/NewsBus.DownloaderService/Dockerfile
    environment:
      - "NewsBusCosmosDbConnectionString=${NewsBusCosmosDbConnectionString}"
      - "NewsBusQueueConnectionString=${NewsBusQueueConnectionString}"
      - "NewsBusStorageConnetionString=${NewsBusStorageConnetionString}"
    ports:
      - 8000:80
