apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloader
  template:
    metadata:
      labels:
        app: downloader
    spec:
      containers:
      - name: downloader
        image: mental001/newsbusdownloaderservice
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: NewsBusCosmosDbConnectionString
          valueFrom:
            secretKeyRef:
              name: newsbus-secret
              key: NewsBusCosmosDbConnectionString
        - name: NewsBusQueueConnectionString
          valueFrom:
            secretKeyRef:
              name: newsbus-secret
              key: NewsBusQueueConnectionString
        - name: NewsBusStorageConnetionString
          valueFrom:
            secretKeyRef:
              name: newsbus-secret
              key: NewsBusStorageConnetionString
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: downloader-service
spec:
  type: NodePort
  selector:
    app: downloader
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 30000


