apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
      - name: watcher
        image: mental001/newsbuswatcherservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: NewsBusCosmosDbConnectionString
          valueFrom:
            secretKeyRef:
              name: newsbus-secret
              key: NewsBusCosmosDbConnectionString
        - name: NewsBusQueueConnectionString
          valueFrom:
            secretKeyRef:
              name: newsbus-secret
              key: NewsBusQueueConnectionString
        - name: NewsBusStorageConnetionString
          valueFrom:
            secretKeyRef:
              name: newsbus-secret
              key: NewsBusStorageConnetionString
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: wactcher-service
spec:
  type: NodePort
  selector:
    app: watcher
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 80
    nodePort: 31000

