name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push WatcherService
        uses: docker/build-push-action@v3
        with:
          file: ./src/NewsBus.WatcherService/Dockerfile
          push: true
          tags: mental001/newsbuswatcherservice:latest
      - name: Build and push DownloaderService
        uses: docker/build-push-action@v3
        with:
          file: ./src/NewsBus.DownloaderService/Dockerfile
          push: true
          tags: mental001/newsbusdownloaderservice:latest
